### PR TITLE
Remove JSON exposition format support

### PR DESCRIPTION
**Pull request by grobie**
JSON has been deprecated as exposition format long time ago. Time to
remove support from client_ruby.

@brian-brazil @fabxc

### CODE REVIEW

**Comment by brian-brazil** [comment]
The tests seem to be failing, otherwise :+1:

**Comment by fabxc** [comment]
:+1: for removing it

**Comment by grobie** [comment]
@brian-brazil Yeah, unfortunately they broke the `rack-test` gem compatibility with 1.9.3. I'll see if locking the version is possible. I have a pre-commit hook to run the tests and they pass fine on ruby 2.x.

**Comment by grobie** [comment]
Tests are green. Travis issues -.-

**Pull request merged**
