### PR TITLE
Convert to CircleCI for build testing

### PR DESCRIPTION
**Pull request by SuperQ**
Replace Travis with CircleCI for testing.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by dmagliola** [comment]
Legend. Thank you so much for the extremely quick response!!

**Review by dmagliola — APPROVED** [review]

**Comment by SuperQ** [comment]
I would double check to make sure everything is working as expected. I noticed some coveralls errors in the CI output.

**Comment by dmagliola** [comment]
Yeah, I can take a look at that. The crucial bit for me what the part I didn't have permissions for, which you've done.
Thank you :)

**Comment by dmagliola** [comment]
Sorry @SuperQ , that comment took a bit of time to address...
My suggestion here: https://github.com/prometheus/client_ruby/pull/239

**Pull request merged**
