### PR TITLE
client/push: add basic auth

### PR DESCRIPTION
**Pull request by josephholsten**
I should mention that these changes to request make me want to cry. So any alternatives would be much appreciated!

### CODE REVIEW

**Comment by josephholsten** [comment]
ok, so I just need to build an assertion that the http double received the right kind of net/http request. ugh.

**Comment by 9to6** [comment]
Hello.
Why this PR it not merged yet?
any problems?

**Comment by grobie** [comment]
Fixed in47a6366c45727b2709ac059c6742c31f5369c595.

**Comment by josephholsten** [comment]
Woo, thanks!

**Pull request closed without merging**
