### PR TITLE
Support http(s) option for net/http

### PR DESCRIPTION
**Pull request by ganmacs**
Use `Net::HTTP.start` so that pushgateway can set variable net/http options.

ref: https://github.com/fluent/fluent-plugin-prometheus_pushgateway/pull/2

https://github.com/ruby/ruby/blob/dec802d8b59900e57e18fa6712caf95f12324aea/lib/net/http.rb#L587-L607

### CODE REVIEW

**Comment by dmagliola** [comment]
Hi @ganmacs,
Sorry for my slow reply.

I'd like to better understand the context behind this change.
Do you have an example of what kind of options this allows you to configure / what was the use case that prompted this PR?

The code looks fine, but i'm a bit concerned that the tests are 100% mocked, so we're not sure whether this actually works. 
The Ruby docs seem to imply it will, but have you tested this actually hitting the Push Gateway successfully?

**Comment by ganmacs** [comment]
Thanks for your reply.

I'd like to use this change in https://github.com/fluent/fluent-plugin-prometheus_pushgateway/pull/2.

> Do you have an example of what kind of options this allows you to configure / what was the use case that prompted this PR?

For example, in the situation where we need to communicate to pushgateway from client through ALB. and the ALB required TLS communication.
client -(HTTPS)-> ALB -(HTTP)-> pushgateway

this is an example using nginx and Net::HTTP.start's verify_tls option.
https://github.com/ganmacs/playground/tree/68f5770daf86c1d95a3ed488d78424d9a0b37af3/prometheus/pushgateway
 
The case where we set verify_tls option to pushgateway(Net::HTTP) client.
<details>

```
pushgateway_1  | level=info ts=2020-02-26T03:31:21.315Z caller=main.go:81 msg="starting pushgateway" version="(version=1.0.1, branch=HEAD, revision=793293bdadd51fdaca69de5bb25637b0f93b656b)"
pushgateway_1  | level=info ts=2020-02-26T03:31:21.315Z caller=main.go:82 build_context="(go=go1.13.5, user=root@0489a6432d5d, date=20191220-22:39:32)"
pushgateway_1  | level=info ts=2020-02-26T03:31:21.317Z caller=main.go:142 listen_address=:9091
fluentd_1      | 2020-02-26 03:31:22 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluentd_1      | 2020-02-26 03:31:22 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.3'
fluentd_1      | 2020-02-26 03:31:22 +0000 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
fluentd_1      | 2020-02-26 03:31:22 +0000 [info]: gem 'fluentd' version '1.9.2'
fluentd_1      | 2020-02-26 03:31:22 +0000 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
fluentd_1      | 2020-02-26 03:31:22 +0000 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
fluentd_1      | 2020-02-26 03:31:22 +0000 [info]: using configuration file: <ROOT>
fluentd_1      |   <source>
fluentd_1      |     @type dummy
fluentd_1      |     tag "dummy"
fluentd_1      |     dummy [{"message":1}]
fluentd_1      |   </source>
fluentd_1      |   <source>
fluentd_1      |     @type prometheus
fluentd_1      |   </source>
fluentd_1      |   <filter dummy>
fluentd_1      |     @type prometheus
fluentd_1      |     <labels>
fluentd_1      |       host ${hostname}
fluentd_1      |       tag ${tag}
fluentd_1      |     </labels>
fluentd_1      |     <metric>
fluentd_1      |       type counter
fluentd_1      |       name nginx_proxy_request_length_total_bytes
fluentd_1      |       desc nginx proxy request length bytes
fluentd_1      |       key message
fluentd_1      |     </metric>
fluentd_1      |   </filter>
fluentd_1      |   <source>
fluentd_1      |     @type prometheus_monitor
fluentd_1      |   </source>
fluentd_1      |   <match dummy>
fluentd_1      |     @type prometheus_pushgateway
fluentd_1      |     gateway "https://nginx:443"
fluentd_1      |     job_name "job1"
fluentd_1      |     tls_verify_mode none
fluentd_1      |   </match>
fluentd_1      | </ROOT>
fluentd_1      | 2020-02-26 03:31:22 +0000 [info]: starting fluentd-1.9.2 pid=7 ruby="2.6.5"
fluentd_1      | 2020-02-26 03:31:22 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/bundle/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
fluentd_1      | 2020-02-26 03:31:23 +0000 [info]: adding filter pattern="dummy" type="prometheus"
fluentd_1      | 2020-02-26 03:31:23 +0000 [info]: adding match pattern="dummy" type="prometheus_pushgateway"
fluentd_1      | 2020-02-26 03:31:23 +0000 [info]: adding source type="dummy"
fluentd_1      | 2020-02-26 03:31:23 +0000 [warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
fluentd_1      | 2020-02-26 03:31:23 +0000 [warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
fluentd_1      | 2020-02-26 03:31:23 +0000 [info]: adding source type="prometheus"
fluentd_1      | 2020-02-26 03:31:23 +0000 [info]: adding source type="prometheus_monitor"
fluentd_1      | 2020-02-26 03:31:23 +0000 [info]: #0 starting fluentd worker pid=17 ppid=7 worker=0
fluentd_1      | 2020-02-26 03:31:23 +0000 [info]: #0 fluentd worker is now running worker=0
nginx_1        | 172.17.0.4 - - [26/Feb/2020:03:31:26 +0000] "POST /metrics/job/job1:0 HTTP/1.1" 200 0 "-" "Ruby" "-"
nginx_1        | 172.17.0.4 - - [26/Feb/2020:03:31:29 +0000] "POST /metrics/job/job1:0 HTTP/1.1" 200 0 "-" "Ruby" "-"
nginx_1        | 172.17.0.4 - - [26/Feb/2020:03:31:32 +0000] "POST /metrics/job/job1:0 HTTP/1.1" 200 0 "-" "Ruby" "-"
nginx_1        | 172.17.0.4 - - [26/Feb/2020:03:31:35 +0000] "POST /metrics/job/job1:0 HTTP/1.1" 200 0 "-" "Ruby" "-"
nginx_1        | 172.17.0.4 - - [26/Feb/2020:03:31:38 +0000] "POST /metrics/job/job1:0 HTTP/1.1" 200 0 "-" "Ruby" "-"
```

</details>

The case where we didn't set verify_tls option to pushgateway(Net::HTTP) client.

<details>

```
pushgateway_1  | level=info ts=2020-02-26T03:31:53.493Z caller=main.go:81 msg="starting pushgateway" version="(version=1.0.1, branch=HEAD, revision=793293bdadd51fdaca69de5bb25637b0f93b656b)"
pushgateway_1  | level=info ts=2020-02-26T03:31:53.493Z caller=main.go:82 build_context="(go=go1.13.5, user=root@0489a6432d5d, date=20191220-22:39:32)"
pushgateway_1  | level=info ts=2020-02-26T03:31:53.494Z caller=main.go:142 listen_address=:9091
fluentd_1      | 2020-02-26 03:31:54 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluentd_1      | 2020-02-26 03:31:54 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.3'
fluentd_1      | 2020-02-26 03:31:54 +0000 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
fluentd_1      | 2020-02-26 03:31:54 +0000 [info]: gem 'fluentd' version '1.9.2'
fluentd_1      | 2020-02-26 03:31:54 +0000 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
fluentd_1      | 2020-02-26 03:31:54 +0000 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
fluentd_1      | 2020-02-26 03:31:54 +0000 [info]: using configuration file: <ROOT>
fluentd_1      |   <source>
fluentd_1      |     @type dummy
fluentd_1      |     tag "dummy"
fluentd_1      |     dummy [{"message":1}]
fluentd_1      |   </source>
fluentd_1      |   <source>
fluentd_1      |     @type prometheus
fluentd_1      |   </source>
fluentd_1      |   <filter dummy>
fluentd_1      |     @type prometheus
fluentd_1      |     <labels>
fluentd_1      |       host ${hostname}
fluentd_1      |       tag ${tag}
fluentd_1      |     </labels>
fluentd_1      |     <metric>
fluentd_1      |       type counter
fluentd_1      |       name nginx_proxy_request_length_total_bytes
fluentd_1      |       desc nginx proxy request length bytes
fluentd_1      |       key message
fluentd_1      |     </metric>
fluentd_1      |   </filter>
fluentd_1      |   <source>
fluentd_1      |     @type prometheus_monitor
fluentd_1      |   </source>
fluentd_1      |   <match dummy>
fluentd_1      |     @type prometheus_pushgateway
fluentd_1      |     gateway "https://nginx:443"
fluentd_1      |     job_name "job1"
fluentd_1      |   </match>
fluentd_1      | </ROOT>
fluentd_1      | 2020-02-26 03:31:54 +0000 [info]: starting fluentd-1.9.2 pid=7 ruby="2.6.5"
fluentd_1      | 2020-02-26 03:31:54 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/bundle/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
fluentd_1      | 2020-02-26 03:31:55 +0000 [info]: adding filter pattern="dummy" type="prometheus"
fluentd_1      | 2020-02-26 03:31:55 +0000 [info]: adding match pattern="dummy" type="prometheus_pushgateway"
fluentd_1      | 2020-02-26 03:31:55 +0000 [info]: adding source type="dummy"
fluentd_1      | 2020-02-26 03:31:55 +0000 [warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
fluentd_1      | 2020-02-26 03:31:55 +0000 [warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
fluentd_1      | 2020-02-26 03:31:55 +0000 [info]: adding source type="prometheus"
fluentd_1      | 2020-02-26 03:31:55 +0000 [info]: adding source type="prometheus_monitor"
fluentd_1      | 2020-02-26 03:31:55 +0000 [info]: #0 starting fluentd worker pid=17 ppid=7 worker=0
fluentd_1      | 2020-02-26 03:31:55 +0000 [info]: #0 fluentd worker is now running worker=0
fluentd_1      | 2020-02-26 03:31:58 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:out_prometheus_pushgateway error_class=OpenSSL::SSL::SSLError error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)"
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:996:in `connect'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:1470:in `request'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/prometheus-client-0.9.0/lib/prometheus/client/push.rb:81:in `request'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/prometheus-client-0.9.0/lib/prometheus/client/push.rb:37:in `block in add'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/prometheus-client-0.9.0/lib/prometheus/client/push.rb:85:in `block in synchronize'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/prometheus-client-0.9.0/lib/prometheus/client/push.rb:85:in `synchronize'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/prometheus-client-0.9.0/lib/prometheus/client/push.rb:85:in `synchronize'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/prometheus-client-0.9.0/lib/prometheus/client/push.rb:36:in `add'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/fluent-plugin-prometheus_pushgateway-0.0.2/lib/fluent/plugin/out_prometheus_pushgateway.rb:94:in `block in start'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.9.2/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.9.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
fluentd_1      |   2020-02-26 03:31:58 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.9.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
fluentd_1      | 2020-02-26 03:31:58 +0000 [error]: #0 Timer detached. title=:out_prometheus_pushgateway
```

</details>

**Comment by Sinjo** [comment]
I have a bit of an API concern with the approach taken here - we've just exposed the entire `opt` interface of [`Net::HTTP.start`](https://ruby-doc.org/stdlib-2.7.0/libdoc/net/http/rdoc/Net/HTTP.html#method-c-start) from our gem, which I believe previously didn't expose the internals of the HTTP client we use.

I'm also slightly confused by the use-case you cited. If I understand right, you want to connect to your pushgateway instance via an ALB that only accepts connections protected with TLS. I would have thought supplying an `https` URL to the client would be enough to do that?

**Comment by grobie** [comment]
I agree with @Sinjo here. This increases the interface of the library significantly, and even worse implicitly. This change will make it very hard to make changes internally, as we bind ourselves to the stdlib HTTP client interface.

Which of the TLS options do you actually need to control?

**Comment by SuperQ** [comment]
We've published an official TLS/security guide for Prometheus.

https://prometheus.io/docs/operating/security/#authentication-authorization-and-encryption

For settings, you can see the current state of the node_exporter https library (that will become our common Go implementation).

https://github.com/prometheus/node_exporter/tree/master/https

**Comment by brian-brazil** [comment]
I believe this is about client side, not server side.

**Comment by dmagliola** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
